### ISSUE TITLE
Character names with periods aren't recognized

### ISSUE THREAD

**Issue by jasonmeisel** [piersdeseilligny/betterfountain#20] opened 2019-03-20 23:22 UTC
If a character name has a period in it (e.g. "MR. FOO"), it neither syntax highlights nor appears in the character list (when beginning a new character line).

**Comment by jasonmeisel** [comment] 2019-03-20 23:32
Also, hyphens!

<img width="380" alt="Screen Shot 2019-03-20 at 4 31 53 PM" src="https://user-images.githubusercontent.com/791774/54725814-b1328380-4b2d-11e9-9a98-43f218080f7e.png">

**Comment by piersdeseilligny** [comment] 2019-03-21 19:29
Just added support for this, but I'm not entirely sure how fountain should behave with this. You can force character names with `@`, (aka `@GREY-HAIRED MAN`) but I don't know if special characters (like `-`,`'`, ect...) should require the `@`.

**Comment by DaTedinator** [comment] 2020-01-02 01:59
Not sure if I should make a new issue for this or not, but I would like to voice support for special characters not requiring an @; "GREY-HAIRED MAN" and "WOMAN'S VOICE" should both be character names without needing to be forced. Fountain.io may never say so explicitly, but I think going off of their examples and their repo that's the intended behavior.

**Comment by piersdeseilligny** [comment] 2020-01-03 15:08
I'il update this soon. I'm busy for the next few weeks, but will definitely add support for this as soon as possible. It might involve some light refactoring though as it seems to make more sense to exclude characters which can't appear in character names, rather than include all those which can.

**Comment by piersdeseilligny** [comment] 2020-11-23 01:07
Fixed by 1.7.0, now in the marketplace!

**Closed as completed** 2020-11-23 01:07 UTC
Labels: bug
