### ISSUE TITLE
Live Margins in editor

### ISSUE THREAD

**Issue by brandonkal** [piersdeseilligny/betterfountain#87] opened 2020-10-22 21:46 UTC
Is this possible?
I don't mind it but my peers (script writing programmers are rare) are not a fan of the dual-pane requirement.

**Comment by piersdeseilligny** [comment] 2020-10-22 22:00
Yep I know, it's not the best user experience there is, and I would really love it if that were possible, however it's not currently because of a bug in vscode: https://github.com/microsoft/vscode/issues/32856 :/ 

I'm thinking of looking at ways of directly editing the preview though by showing the caret in it, and sending keystrokes in the preview to the editor - which would give the illusion of directly editing the preview. It's just an idea for the moment, with absolutely no timeframe, but it's a way this might be possible (until microsoft fixes that bug).


(P.S. i'm going to close this issue, as it's a duplicate of https://github.com/microsoft/vscode/issues/32856)

**Closed as completed by piersdeseilligny** 2020-10-22 22:00 UTC

**Comment by brandonkal** [comment] 2020-10-22 22:10
I have not installed [this Unotes extension](https://marketplace.visualstudio.com/items?itemName=ryanmcalister.Unotes) but it might be a good base and seems to completely replace the default editor.

Editing in the preview pane could be an interesting approach.

Personally I appreciate being able to use the vim emulation extension but wish VSCode could handle some WYSIWG view a la [Typora](https://typora.io)

**Comment by piersdeseilligny** [comment] 2020-10-22 22:29
Yep it'd technically be possible to have a complete replacement of the default editor, but then you'd lose any features added by any other extensions (like spell checking) and integrated parts of vscode's editor, like autocomplete etc... which isn't ideal.
